automatic merge

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,6 +38,15 @@ jobs:
                 git checkout production
                 git pull --rebase origin main  # Ensure the latest main changes are on production
 
+                # Merge main into production (automatically resolving some conflicts)
+                git merge origin/main -m "Merging main into production"
+                # In case of merge conflicts, use git merge --abort or handle conflicts automatically
+                if [ $? -ne 0 ]; then
+                git merge --abort  # Abort the merge if there are conflicts
+                echo "Merge failed, conflicts need to be resolved."
+                exit 1  # Fail the CI job if conflicts need to be handled manually
+                fi
+
         - name: Install dependencies and build
           working-directory: pages/FrontEnd
           run: |
